apiVersion: v1
kind: Service
metadata:
  name: k8s-test-service
spec:
  selector:
    app: k8s-test
    env: test
  ports:
    - port: 80			# 服务端口, 内部可访问
      targetPort: 8080		# 目标端口, 此处指的是pod的8080端口
      nodePort: 30080		# 节点端口, 外部可访问
      protocol: TCP
  type: NodePort
